### ISSUE TITLE
I've been trying to make a triangle output in vulkan for whole 3 days with this

### ISSUE THREAD

**Issue by cocomeIon** [nyorain/swa#2]
How should your example-vulkan-loop.c be extentended to do that? When I tried to do that there was state.n_buf=5 and command buffers were empty and it crashed on resize and didn't show anything.

**Comment by cocomeIon** [comment]
Ok, this is just me misunderstanding something.

**Comment by nyorain** [comment]
If you feel like this misunderstanding could be improved by better documentation in swa let me know. If others could run into the same problem, feel free to post here what you discovered :)
