### ISSUE TITLE
Fail to build with gcc and buildtype=release

### ISSUE THREAD

**Issue by Unesty** [nyorain/swa#4]
ninja: Entering directory `build/'
[1/11] Compiling C object libswa.a.p/src_swa_x11.c.o
FAILED: libswa.a.p/src_swa_x11.c.o 
gcc -Ilibswa.a.p -I. -I.. -I../src -Iinclude -I../include -I../subprojects/dlg/include -Isubprojects/pml -I../subprojects/pml -I/usr/include/libdrm -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c11 -O3 -Wno-unused-parameter -Wno-unused-function -Wno-missing-braces -Wundef -Wvla '-DDLG_BASE_PATH="/tmp/user/Downloads/swa/"' -fPIC -pthread -MD -MQ libswa.a.p/src_swa_x11.c.o -MF libswa.a.p/src_swa_x11.c.o.d -o libswa.a.p/src_swa_x11.c.o -c ../src/swa/x11.c
../src/swa/x11.c: In function 'display_create_window':
../src/swa/x11.c:1642:22: error: 'visual_format' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 1642 |   win->buffer.format = visual_format;
      |   ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
../src/swa/x11.c:1643:52: error: 'visual_scanline_pad' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 1643 |   win->buffer.scanline_align = visual_scanline_pad / 8;
      |                                ~~~~~~~~~~~~~~~~~~~~^~~
cc1: all warnings being treated as errors
[2/11] Compiling C object libswa.a.p/src_swa_wayland.c.o
FAILED: libswa.a.p/src_swa_wayland.c.o 
gcc -Ilibswa.a.p -I. -I.. -I../src -Iinclude -I../include -I../subprojects/dlg/include -Isubprojects/pml -I../subprojects/pml -I/usr/include/libdrm -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c11 -O3 -Wno-unused-parameter -Wno-unused-function -Wno-missing-braces -Wundef -Wvla '-DDLG_BASE_PATH="/tmp/user/Downloads/swa/"' -fPIC -pthread -MD -MQ libswa.a.p/src_swa_wayland.c.o -MF libswa.a.p/src_swa_wayland.c.o.d -o libswa.a.p/src_swa_wayland.c.o -c ../src/swa/wayland.c
In function 'create_pool_file',
    inlined from 'buffer_init.constprop' at ../src/swa/wayland.c:268:11:
../src/swa/wayland.c:231:3: error: attempt to free a non-heap object 'name' [-Werror=free-nonheap-object]
  231 |   free(name);
      |   ^~~~~~~~~~
../src/swa/wayland.c:238:3: error: attempt to free a non-heap object 'name' [-Werror=free-nonheap-object]
  238 |   free(name);
      |   ^~~~~~~~~~
../src/swa/wayland.c:245:3: error: attempt to free a non-heap object 'name' [-Werror=free-nonheap-object]
  245 |   free(name);
      |   ^~~~~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.

**Comment by nyorain** [comment]
Good catch, thanks! The second set of errors indicated actual code errors. They are fixed now.
